# Generated by Django 4.2.6 on 2024-01-31 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dealer_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_address', models.TextField(max_length=20)),
                ('p_area', models.CharField(max_length=20)),
                ('p_type', models.CharField(choices=[('BUNGLOW', 'BUNGLOW'), ('ROW_HOUSE', 'ROW_HOUSE'), ('APPARTMENT', 'APPARTMENT')], default='APPARTMENT', max_length=15)),
                ('p_furnishingtype', models.CharField(choices=[('FULLY', 'FULLY'), ('SEMI', 'SEMI'), ('NOT', 'NOT')], default='NOT', max_length=20)),
                ('p_age_type', models.CharField(choices=[('month', 'month'), ('year', 'year')], default='month', max_length=20)),
                ('p_age', models.PositiveIntegerField()),
                ('p_direction', models.CharField(choices=[('north', 'north'), ('south', 'south'), ('east', 'east'), ('west', 'west')], max_length=20)),
                ('p_rentprize', models.PositiveIntegerField()),
                ('a_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=10)),
                ('password1', models.CharField(max_length=15)),
                ('password2', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='media/p_images')),
                ('proty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerapp.property')),
            ],
        ),
    ]
