# Generated by Django 4.2.6 on 2024-02-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='p_image',
            field=models.ImageField(upload_to='p_images'),
        ),
    ]
