# Generated by Django 4.2.6 on 2024-02-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0002_alter_image_p_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dealer_profile',
        ),
    ]
