# Generated by Django 4.2.6 on 2024-02-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='buyername',
            new_name='user',
        ),
    ]
