# Generated by Django 4.2.6 on 2024-02-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0003_delete_dealer_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyerapp', '0002_rename_buyername_bookingrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='prop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dealerapp.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
